# Generated by Django 2.2.4 on 2019-11-19 13:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
                ('quantity_integer', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('link_text', models.CharField(blank=True, max_length=200, null=True)),
                ('price_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('description_text', models.CharField(blank=True, max_length=400, null=True)),
                ('location_text', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor_text', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor_id_text', models.CharField(blank=True, max_length=200, null=True)),
                ('manufacturer_text', models.CharField(blank=True, max_length=200, null=True)),
                ('manufacturer_id_text', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_text', models.CharField(max_length=30)),
                ('type_text', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity_integer', models.PositiveIntegerField()),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('item_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
            ],
            options={
                'ordering': ['-last_modified_date'],
            },
        ),
    ]
