# Generated by Django 3.0.2 on 2020-02-11 15:48

from django.db import migrations


class Migration(migrations.Migration):
		atomic = False

		dependencies = [
				('inventory', '0002_auto_20200211_1527'),
		]

		operations = [
			migrations.RenameModel(old_name='Item',new_name='Items',),
		]
